### ISSUE TITLE
success pop up ambiguity check; opens even after clicking on text

### ISSUE THREAD

**Issue by vaibhav18matere** [siddhigate/roadmap-runner#46]
- 1. When you click on text of the content, on any course roadmap (see the attached image for more clarity), then it directly shows the `pop up`. The idea should be when user clicks on the checkbox then and then only the pop-up should open. That should be the intended purpose of keeping the `checkbox` there.
 
![image](https://user-images.githubusercontent.com/90924055/212746774-7fca8494-da91-4afc-a2b1-718a6eb0a1b5.png)

- 2. But if you keeping the same UX, then add `cursor:pointer` for that list items to make the user experience smoother just like how you are doing it for checkbox and link icons.

**Comment by siddhigate** [comment]
Hey Vaibhav, thanks for raising this issue!
